// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Tbproduct struct {
	ID        []byte
	Descricao string
	Categoria string
}

type Tbuser struct {
	ID        string
	Name      string
	Email     string
	Birthdate time.Time
}
