// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const checkEmail = `-- name: CheckEmail :one
select 1
  from tbusers
 where email = ?
`

func (q *Queries) CheckEmail(ctx context.Context, email string) (int32, error) {
	row := q.db.QueryRowContext(ctx, checkEmail, email)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const create = `-- name: Create :execresult
insert into tbusers (
    id, name, email, birthdate
) 
values(
    ?, ?, ?, ?
)
`

type CreateParams struct {
	ID        string
	Name      string
	Email     string
	Birthdate time.Time
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, create,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Birthdate,
	)
}

const delete = `-- name: Delete :execrows
delete from tbusers 
where id = ?
`

func (q *Queries) Delete(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, delete, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const get = `-- name: Get :one
select id, name, email, birthdate from tbusers where id = ?
`

func (q *Queries) Get(ctx context.Context, id string) (Tbuser, error) {
	row := q.db.QueryRowContext(ctx, get, id)
	var i Tbuser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Birthdate,
	)
	return i, err
}

const list = `-- name: List :many
select id, name, email, birthdate
from tbusers
order by name
`

func (q *Queries) List(ctx context.Context) ([]Tbuser, error) {
	rows, err := q.db.QueryContext(ctx, list)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tbuser
	for rows.Next() {
		var i Tbuser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Birthdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :exec
update tbusers 
set name = ?, email = ?, birthdate = ?
where id = ?
`

type UpdateParams struct {
	Name      string
	Email     string
	Birthdate time.Time
	ID        string
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.ExecContext(ctx, update,
		arg.Name,
		arg.Email,
		arg.Birthdate,
		arg.ID,
	)
	return err
}
